### ISSUE TITLE
GPPC import error

### ISSUE THREAD

**Issue by Weirwindle** [moxxos/gppc#1]
This started happening in last 3 days
Thank you for this project!

Traceback (most recent call last):
  File "C:\Users\Tim\anaconda3\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\anaconda3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\anaconda3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\anaconda3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tim\anaconda3\Scripts\gppc.exe\__main__.py", line 4, in <module>
  File "C:\Users\Tim\anaconda3\Lib\site-packages\gppc\__init__.py", line 15, in <module>
    from gppc._gppc import _main, _search_print as search
  File "C:\Users\Tim\anaconda3\Lib\site-packages\gppc\_gppc.py", line 27, in <module>
    from gppc._item import Item
  File "C:\Users\Tim\anaconda3\Lib\site-packages\gppc\_item.py", line 18, in <module>
    _RAW_LIST = requests.get(_MAP_API, headers=_REQUEST_HEADER, timeout=100).json()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\anaconda3\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by moxxos** [comment]
thanks letting me know and using gppc! i will look into this asap

**Comment by Weirwindle** [comment]
Thank you. I have made another using requests to "https://prices.runescape.wiki/api/v1/osrs/timeseries" to get historic price data, but it takes a while and I don't want to push more than 1 request per second.
I monitor for price drops with GPPC and OSRSBytes.
Once every 30 minutes I use GPPC to grab time data for 140 items and calculate a polyfit trend line and standard deviation to each item. This shows me what the current price should be. I then compare this to OSRSBytes live data and check which prices are far lower then they should be.
If lower by more than 3.5 standard deviations, my script sends a notification to my phone so that I can buy buy buy.

**Comment by moxxos** [comment]
sorry this took a while but i just needed to update the user agent version lol. very cool project btw!
